[build-system]
requires = ["setuptools", "wheel", "GitPython"]
# See setup.cfg
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py36']
exclude = '(/venv/|/build/|/dist/|/ddnswolf.egg-info/)'
